RTS_Pathfinder: Map Class Reference
Map Class Reference
#include <Map.hpp>
Public Member Functions
Map ()=default
Construct an empty map param none return none.
bool loadFromJson (const std::string &filepath)
Load a map from a RiskyLab Tilemap JSON file.
bool saveToJson (const std::string &filepath) const
Save map to a RiskyLab Tilemap JSON file.
bool savePathToJson (const std::string &filepath, const std::vector< Position > &path) const
Save path positions to JSON file.
bool loadPathFromJson (const std::string &filepath, std::vector< Position > &outPath) const
Load path positions from JSON file.
void generateRandom (int rows, int cols, float wallRatio=0.2f)
Generate a random map.
CellType getCellType (Position p) const
Get the cell type at a position.
bool isWalkable (Position p) const
Check if a position is walkable.
bool isInBounds (Position p) const
Check if a position is within map bounds.
int numRows () const
Get number of rows.
int numCols () const
Get number of columns.
std::vector< Position > getNeighbors (Position p) const
Get all walkable cells from a position (4-directions).
Position findStart () const
Find the start position in the map.
Position findTarget () const
Find the target position in the map.
void setCell (Position p, CellType type)
Set a cell to a specific type.
Public Attributes
std::vector< std::vector< CellType > > m_grid
int m_numRows = 0
int m_numCols = 0
Detailed Description
Definition at line 16 of file Map.hpp.
Constructor & Destructor Documentation
Map()
Map::Map () default
Construct an empty map param none return none.
Member Function Documentation
findStart()
Position Map::findStart () const
Find the start position in the map.
Returns
Start position (cell value == 0), or {-1, -1} if not found
Definition at line 149 of file Map.cpp.
{
    for (int r = 0; r < m_numRows; ++r)
    {
        for (int c = 0; c < m_numCols; ++c)
        {
            if (m_grid[r][c] == CellType::Start)
                {
                    return {r, c};
                }
        }
    }
    return {-1, -1};
}
References m_grid, m_numCols, m_numRows, and Start.
Referenced by main().
findTarget()
Position Map::findTarget () const
Find the target position in the map.
Returns
Target position (cell value == 8), or {-1, -1} if not found
Definition at line 164 of file Map.cpp.
{
    for (int r = 0; r < m_numRows; ++r)
    {
        for (int c = 0; c < m_numCols; ++c)
        {
            if (m_grid[r][c] == CellType::Target)
            {
                return {r, c};
            }
        }
    }
    return {-1, -1};
}
References m_grid, m_numCols, m_numRows, and Target.
Referenced by main().
generateRandom()
void Map::generateRandom (int rows, int cols, float wallRatio = 0.2f)
Generate a random map.
Parameters
rows Number of rows in the map
cols Number of columns in the map
wallRatio Ratio of walls to total cells (default 0.2f = 20%)
Definition at line 63 of file Map.cpp.
{
    // Return early if dimensions are invalid
    if (rows <= 0 || cols <= 0)
    {
        std::cerr << "Error: Map dimensions must be positive" << std::endl;
        return;
    }
    m_numRows = rows;
    m_numCols = cols;
    // Initialize grid with all open cells
    m_grid.assign(m_numRows, std::vector<CellType>(m_numCols, CellType::Open));
    // Randomly place walls based on the specified ratio using a Bernoulli distribution
    std::random_device rd;
    std::mt19937 gen(rd());
    std::bernoulli_distribution makeWall(wallRatio);
    for (auto &row : m_grid)
    {
        for (auto &cell : row)
        {
            if (makeWall(gen))
            {
                cell = CellType::Elevated;
            }
        }
    }
    // Place start at bottom-left corner
    m_grid[m_numRows - 1][0] = CellType::Start;
    // Place target at top-right corner
    m_grid[0][m_numCols - 1] = CellType::Target;
}
References Elevated, m_grid, m_numCols, m_numRows, Open, Start, and Target.
Referenced by main().
getCellType()
CellType Map::getCellType (Position p) const
Get the cell type at a position.
Parameters
p Position to query
Returns
Cell type at the position, or Open if out of bounds
Definition at line 100 of file Map.cpp.
{
    if (!isInBounds(p))
    {
        return CellType::Open; // Treat out-of-bounds as open for pathfinding
    }
    return m_grid[p.row][p.col];
}
References Position::col, isInBounds(), m_grid, Open, and Position::row.
Referenced by Renderer::printMap(), and ConsoleApp::replaceMarker().
getNeighbors()
std::vector< Position > Map::getNeighbors (Position p) const
Get all walkable cells from a position (4-directions).
Parameters
p Position
Returns
Vector of walkable neighbor positions
Definition at line 126 of file Map.cpp.
{
    std::vector<Position> neighbors; // return object
    Position directions[] = {
        {p.row - 1, p.col}, // up
        {p.row + 1, p.col}, // down
        {p.row, p.col - 1}, // left
        {p.row, p.col + 1}  // right
    };
    for (const auto &dir : directions)
    {
        if (isWalkable(dir))
        {
            neighbors.push_back(dir);
        }
    }
    return neighbors;
}
References Position::col, isWalkable(), and Position::row.
Referenced by Pathfinder::aStarSearch().
isInBounds()
bool Map::isInBounds (Position p) const
Check if a position is within map bounds.
Parameters
p Position to check
Returns
true if position is within bounds
Definition at line 121 of file Map.cpp.
{
    return ((p.row >= 0) && (p.row < m_numRows) && (p.col >= 0) && (p.col < m_numCols));
}
References Position::col, m_numCols, m_numRows, and Position::row.
Referenced by ConsoleApp::executePathfinding(), getCellType(), isWalkable(), and setCell().
isWalkable()
bool Map::isWalkable (Position p) const
Check if a position is walkable.
Parameters
p Position to check
Returns
true if position is walkable (not Elevated and in bounds)
Definition at line 110 of file Map.cpp.
{
    if (!isInBounds(p))
    {
        return false; // Out-of-bounds is not walkable
    }
    CellType cell = m_grid[p.row][p.col];
    return cell != CellType::Elevated;
}
References Position::col, Elevated, isInBounds(), m_grid, and Position::row.
Referenced by Pathfinder::aStarSearch(), getNeighbors(), and main().
loadFromJson()
bool Map::loadFromJson (const std::string & filepath)
Load a map from a RiskyLab Tilemap JSON file.
Parameters
filepath Path to the JSON file
Returns
true if load succeeded, false otherwise
Definition at line 6 of file Map.cpp.
{
    std::vector<int> flatData;
    int width = 0;
    int height = 0;
    if (!JsonLoader::loadMap(filepath, flatData, width, height))
    {
        return false;
    }
    m_numCols = width;
    m_numRows = height;
    m_grid.assign(m_numRows, std::vector<CellType>(m_numCols, CellType::Open));
    for (int r = 0; r < m_numRows; ++r)
    {
        for (int c = 0; c < m_numCols; ++c)
        {
            const int value = flatData[r * m_numCols + c];
            switch (value)
            {
            case static_cast<int>(CellType::Start):
                m_grid[r][c] = CellType::Start;
                break;
            case static_cast<int>(CellType::Elevated):
                m_grid[r][c] = CellType::Elevated;
                break;
            case static_cast<int>(CellType::Target):
                m_grid[r][c] = CellType::Target;
                break;
            case static_cast<int>(CellType::Open):
            default:
                m_grid[r][c] = CellType::Open;
                break;
            }
        }
    }
    return true;
}
References Elevated, JsonLoader::loadMap(), m_grid, m_numCols, m_numRows, Open, Start, and Target.
Referenced by main().
loadPathFromJson()
bool Map::loadPathFromJson (const std::string & filepath, std::vector< Position > & outPath) const
Load path positions from JSON file.
Parameters
filepath Path to input JSON file
outPath Loaded path positions
Returns
true if load succeeded
Definition at line 58 of file Map.cpp.
{
    return JsonLoader::loadPath(filepath, outPath);
}
References JsonLoader::loadPath().
Referenced by main().
numCols()
int Map::numCols () const inline
Get number of columns.
Returns
Number of columns
Definition at line 95 of file Map.hpp.
{ return m_numCols; }
References m_numCols.
Referenced by main(), Renderer::printMap(), and ConsoleApp::replaceMarker().
numRows()
int Map::numRows () const inline
Get number of rows.
Returns
Number of rows
Definition at line 89 of file Map.hpp.
{ return m_numRows; }
References m_numRows.
Referenced by main(), Renderer::printMap(), and ConsoleApp::replaceMarker().
savePathToJson()
bool Map::savePathToJson (const std::string & filepath, const std::vector< Position > & path) const
Save path positions to JSON file.
Parameters
filepath Path to output JSON file
path Path positions to save
Returns
true if save succeeded
Definition at line 53 of file Map.cpp.
{
    return JsonLoader::savePath(filepath, path);
}
References JsonLoader::savePath().
Referenced by main().
saveToJson()
bool Map::saveToJson (const std::string & filepath) const
Save map to a RiskyLab Tilemap JSON file.
Parameters
filepath Path to the output JSON file
Returns
true if save succeeded, false otherwise
Definition at line 48 of file Map.cpp.
{
    return JsonLoader::saveMap(filepath, m_grid);
}
References m_grid, and JsonLoader::saveMap().
Referenced by main().
setCell()
void Map::setCell (Position p, CellType type)
Set a cell to a specific type.
Parameters
p Position to set
type Cell type to set
Definition at line 179 of file Map.cpp.
{
    if (isInBounds(p))
    {
        m_grid[p.row][p.col] = type;
    }
}
References Position::col, isInBounds(), m_grid, and Position::row.
Referenced by ConsoleApp::replaceMarker().
Member Data Documentation
m_grid
std::vector<std::vector<CellType> > Map::m_grid
Definition at line 123 of file Map.hpp.
Referenced by findStart(), findTarget(), generateRandom(), getCellType(), isWalkable(), loadFromJson(), saveToJson(), and setCell().
m_numCols
int Map::m_numCols = 0
Definition at line 125 of file Map.hpp.
Referenced by findStart(), findTarget(), generateRandom(), isInBounds(), loadFromJson(), and numCols().
m_numRows
int Map::m_numRows = 0
Definition at line 124 of file Map.hpp.
Referenced by findStart(), findTarget(), generateRandom(), isInBounds(), loadFromJson(), and numRows().
The documentation for this class was generated from the following files:
include/Map.hpp
src/Map.cpp