RTS_Pathfinder: Pathfinder Class Reference
Pathfinder Class Reference
#include <PathFinder.hpp>
Classes
struct Node
Node structure for A* algorithm.
struct CompareNode
Comparison functor for priority queue (min-heap by f-cost).
Public Member Functions
Pathfinder ()=default
Construct a Pathfinder instance.
PathResult findPath (const Map &map, Position start, Position target)
Find a path using A* algorithm.
Private Member Functions
float heuristic (Position a, Position b) const
Calculate Manhattan distance heuristic.
PathResult aStarSearch (const Map &map, Position start, Position target)
Internal A* implementation.
std::vector< Position > reconstructPath (const std::unordered_map< Position, Position, Position::PositionHash > &parentMap, Position start, Position target) const
Reconstruct path from parent pointers.
Detailed Description
Definition at line 18 of file PathFinder.hpp.
Constructor & Destructor Documentation
Pathfinder()
Pathfinder::Pathfinder () default
Construct a Pathfinder instance.
Member Function Documentation
aStarSearch()
PathResult Pathfinder::aStarSearch (const Map & map, Position start, Position target) private
Internal A* implementation.
Parameters
map The battlefield map
start Starting position
target Target position
Returns
PathResult
Definition at line 16 of file PathFinder.cpp.
{
    PathResult result;
    if (!map.isWalkable(start))
    {
        result.errorMessage = "Start position is not walkable";
        return result; // Early exit
    }
    if (!map.isWalkable(target))
    {
        result.errorMessage = "Target position is not walkable";
        return result; // Early exit
    }
    if (start == target)
    {
        result.success = true;
        result.path.push_back(start);
        return result; // Early exit
    }
    std::priority_queue<Node, std::vector<Node>, CompareNode> openSet; // unexplored nodes
    std::unordered_map<Position, Node, Position::PositionHash> closedSet; // explored nodes
    std::unordered_map<Position, Node, Position::PositionHash> nodeMap; // nodes by position
    std::unordered_map<Position, Position, Position::PositionHash> parentMap; // parent pointers for path reconstruction
    Node startNode;
    startNode.m_pos = start;
    startNode.m_gCost = 0.0f;
    startNode.m_hCost = heuristic(start, target);
    startNode.m_parent = {-1, -1};
    openSet.push(startNode);
    nodeMap[start] = startNode;
    while (!openSet.empty())
    {
        Node current = openSet.top();
        openSet.pop();
        // If target reached, reconstruct the path and return success
        if (current.m_pos == target)
        {
            result.success = true;
            result.path = reconstructPath(parentMap, start, target);
            return result;
        }
        // Skip if this node has already been explored with a lower f-cost
        if (closedSet.count(current.m_pos) > 0)
        {
            continue;
        }
        // Set current node as explored
        closedSet[current.m_pos] = current;
        // Explore neighbors of the current node
        for (const auto &neighbor : map.getNeighbors(current.m_pos))
        {
            // Skip if neighbor is already explored
            if (closedSet.count(neighbor) > 0)
            {
                continue;
            }
            // Calculate tentative g-cost to neighbor
            float tentativeGCost = current.m_gCost + 1.0f;
            // If neighbor is not in open set or if lower g-cost path is found
            if ((nodeMap.count(neighbor) == 0) || (tentativeGCost < nodeMap[neighbor].m_gCost))
            {
                parentMap[neighbor] = current.m_pos;
                // Update or add neighbor node in open set
                Node neighborNode;
                neighborNode.m_pos = neighbor;
                neighborNode.m_gCost = tentativeGCost;
                neighborNode.m_hCost = heuristic(neighbor, target);
                neighborNode.m_parent = current.m_pos;
                //
                nodeMap[neighbor] = neighborNode;
                openSet.push(neighborNode);
            }
        }
    }
    result.errorMessage = "No path found - target unreachable";
    return result;
}
References PathResult::errorMessage, Map::getNeighbors(), heuristic(), Map::isWalkable(), Pathfinder::Node::m_gCost, Pathfinder::Node::m_hCost, Pathfinder::Node::m_parent, Pathfinder::Node::m_pos, PathResult::path, reconstructPath(), and PathResult::success.
Referenced by findPath().
findPath()
PathResult Pathfinder::findPath (const Map & map, Position start, Position target)
Find a path using A* algorithm.
Parameters
map The battlefield map
start Starting position
target Target position
Returns
PathResult containing the path or error message
Definition at line 11 of file PathFinder.cpp.
{
    return aStarSearch(map, start, target);
}
References aStarSearch().
Referenced by ConsoleApp::executePathfinding().
heuristic()
float Pathfinder::heuristic (Position a, Position b) const private
Calculate Manhattan distance heuristic.
Parameters
a First position
b Second position
Returns
Manhattan distance
Definition at line 4 of file PathFinder.cpp.
{
    // Manhattan distance
    // Using  manhattan as only 4 directions are allowed; no diagonal movement
    return static_cast<float>(std::abs(a.row - b.row) + std::abs(a.col - b.col));
}
References Position::col, and Position::row.
Referenced by aStarSearch().
reconstructPath()
std::vector< Position > Pathfinder::reconstructPath (const std::unordered_map< Position, Position, Position::PositionHash > & parentMap, Position start, Position target) const private
Reconstruct path from parent pointers.
Parameters
parentMap Map of positions to their parents
start Starting position
target Ending position
Returns
Vector representing the path
Definition at line 110 of file PathFinder.cpp.
{
    std::vector<Position> path;
    // Start from the goal and walk backwards through parent pointers.
    Position current = target;
    while (!(current == start))
    {
        // Record current node while traversing backward.
        path.push_back(current);
        // If parent is missing, reconstruction is incomplete; stop safely.
        auto it = parentMap.find(current);
        if (it == parentMap.end())
            break;
        // Move one step toward the start.
        current = it->second;
    }
    // Include start node, then reverse to get start -> target order.
    path.push_back(start);
    std::reverse(path.begin(), path.end());
    return path;
}
Referenced by aStarSearch().
The documentation for this class was generated from the following files:
include/PathFinder.hpp
src/PathFinder.cpp