RTS_Pathfinder: Renderer Class Reference
Renderer Class Reference
#include <Renderer.hpp>
Static Public Member Functions
static void printMap (const Map &map, const std::vector< Position > &path={})
Print the map to console.
static void printPath (const std::vector< Position > &path)
Print a cell positions as path coordinates.
Static Private Member Functions
static char cellToChar (CellType cell)
Convert a cell type to a character.
static bool isTraversedCell (const Position &cell, const std::vector< Position > &path)
Check if a cell is part of the traversed path.
Detailed Description
Definition at line 14 of file Renderer.hpp.
Member Function Documentation
cellToChar()
char Renderer::cellToChar (CellType cell) static private
Convert a cell type to a character.
Parameters
cell Cell type
Returns
Character representation of the cell type
Definition at line 7 of file Renderer.cpp.
{
    switch (cell)
    {
    case CellType::Start:
        return 'S';
    case CellType::Target:
        return 'T';
    case CellType::Elevated:
        return '#';
    case CellType::Open:
    default:
        return '.';
    }
}
References Elevated, Open, Start, and Target.
Referenced by printMap().
isTraversedCell()
bool Renderer::isTraversedCell (const Position & cell, const std::vector< Position > & path) static private
Check if a cell is part of the traversed path.
Parameters
cell Position of the cell to check
path Vector of positions representing the path
Returns
true if the cell is in the path, false otherwise
Definition at line 23 of file Renderer.cpp.
{
    return std::find(path.begin(), path.end(), cell) != path.end();
}
Referenced by printMap().
printMap()
void Renderer::printMap (const Map & map, const std::vector< Position > & path = {}) static
Print the map to console.
Parameters
map Map to print
path Path traversed
Definition at line 28 of file Renderer.cpp.
{
    const char *kYellow = "\033[33m";
    const char *kReset = "\033[0m";
    const int rowWidth = static_cast<int>(std::to_string(map.numRows() - 1).size());
    // Column numbers
    std::cout << std::string(rowWidth + 1, ' ');
    for (int c = 0; c < map.numCols(); ++c)
    {
        std::cout << std::left << std::setw(2) << c;
    }
    std::cout << '\n';
    for (int r = 0; r < map.numRows(); ++r)
    {
        // Row number
        std::cout << std::right << std::setw(rowWidth) << r << ' ';
        for (int c = 0; c < map.numCols(); ++c)
        {
            const Position cell{r, c};
            if (!path.empty() && isTraversedCell(cell, path) &&
                map.getCellType(cell) != CellType::Start &&
                map.getCellType(cell) != CellType::Target)
            {
                std::cout << kYellow << '*' << kReset << ' ';
            }
            else
            {
                std::cout << cellToChar(map.getCellType(cell)) << ' ';
            }
        }
        std::cout << '\n';
    }
}
References cellToChar(), Map::getCellType(), isTraversedCell(), Map::numCols(), Map::numRows(), Start, and Target.
Referenced by ConsoleApp::executePathfinding(), and main().
printPath()
void Renderer::printPath (const std::vector< Position > & path) static
Print a cell positions as path coordinates.
Parameters
path Vector of positions representing the path
Definition at line 65 of file Renderer.cpp.
{
    if (path.empty())
    {
        std::cout << "(empty)";
        return;
    }
    for (size_t i = 0; i < path.size(); ++i)
    {
        const Position &p = path[i];
        std::cout << "(" << p.row << "," << p.col << ")";
        if (i + 1 < path.size())
        {
            std::cout << " -> ";
        }
    }
}
References Position::col, and Position::row.
Referenced by ConsoleApp::executePathfinding().
The documentation for this class was generated from the following files:
include/Renderer.hpp
src/Renderer.cpp