RTS_Pathfinder: ConsoleApp Namespace Reference
ConsoleApp Namespace Reference
Functions
template<typename T>
bool readNumber (const std::string &prompt, T &outValue)
Read a number from console.
Position getPositionFromInput ()
Read a position (row and column) from console. Calls readNumber for each coordinate.
void displayMainMenu ()
Display main menu.
void replaceMarker (Map &map, CellType marker, Position newPosition)
Replace existing marker (start or target) on the map with a new position.
bool executePathfinding (Map &map, Position start, Position target, std::vector< Position > &outPath)
Execute pathfinder.
Function Documentation
displayMainMenu()
void ConsoleApp::displayMainMenu ()
Display main menu.
Definition at line 51 of file main.cpp.
    {
        std::cout
            << "\n=== RTS Pathfinder ===\n"
            << "1. Load map from JSON\n"
            << "2. Generate random map\n"
            << "3. Set start position\n"
            << "4. Set target position\n"
            << "5. Run pathfinding\n"
            << "6. Show current map\n"
            << "7. Save map to JSON\n"
            << "8. Save last path positions\n"
            << "9. Read path positions from file\n"
            << "10. Exit\n"
            << "Select option: ";
    }
Referenced by main().
executePathfinding()
bool ConsoleApp::executePathfinding (Map & map, Position start, Position target, std::vector< Position > & outPath)
Execute pathfinder.
Parameters
map Map to traverse
start Start position
target Target position
Definition at line 97 of file main.cpp.
     {
         if (start.row == -1 || target.row == -1)
         {
             std::cerr << "Error: Start or target not set." << std::endl;
             return false;
         }
         if (!map.isInBounds(start) || !map.isInBounds(target))
         {
             std::cerr << "Error: Start or target out of bounds." << std::endl;
             return false;
         }
         std::cout << "Running pathfinding from (" << start.row << "," << start.col
                   << ") to (" << target.row << "," << target.col << ")..." << std::endl;
         Pathfinder pathfinder;
         const PathResult result = pathfinder.findPath(map, start, target);
         if (!result.success)
         {
             std::cerr << "Pathfinding failed: " << result.errorMessage << std::endl;
             return false;
         }
         std::cout << "Path found. Length: " << result.path.size() << std::endl;
         Renderer::printPath(result.path);
         std::cout << '\n';
         std::cout << "Solved map (* = traversed path):" << std::endl;
         Renderer::printMap(map, result.path);
         outPath = result.path;
         return true;
     }
References Position::col, PathResult::errorMessage, Pathfinder::findPath(), Map::isInBounds(), PathResult::path, Renderer::printMap(), Renderer::printPath(), Position::row, and PathResult::success.
Referenced by main().
getPositionFromInput()
Position ConsoleApp::getPositionFromInput ()
Read a position (row and column) from console. Calls readNumber for each coordinate.
Returns
Position struct with the parsed coordinates, or {-1, -1} on failure
Definition at line 35 of file main.cpp.
    {
        int row = -1;
        int col = -1;
        if (!readNumber("Enter row: ", row) || !readNumber("Enter col: ", col))
        {
            return {-1, -1}; // Return invalid position on failure
        }
        return {row, col};
    }
References readNumber().
Referenced by main().
readNumber()
template<typename T> bool ConsoleApp::readNumber (const std::string & prompt, T & outValue)
Read a number from console.
Parameters
prompt Prompt message
outValue Variable to store the parsed number
Returns
true if parsing success
Definition at line 19 of file main.cpp.
    {
        std::cout << prompt;
        std::string line;
        if (!std::getline(std::cin, line))
        {
            return false;
        }
        std::istringstream iss(line);
        return (iss >> outValue) && iss.eof();
    }
Referenced by getPositionFromInput(), and main().
replaceMarker()
void ConsoleApp::replaceMarker (Map & map, CellType marker, Position newPosition)
Replace existing marker (start or target) on the map with a new position.
Parameters
map Map to modify
marker CellType::Start or CellType::Target to replace
newPosition New position for the marker
Definition at line 74 of file main.cpp.
     {
         for (int r = 0; r < map.numRows(); ++r)
         {
             for (int c = 0; c < map.numCols(); ++c)
             {
                 const Position cell{r, c};
                 if (map.getCellType(cell) == marker)
                 {
                     map.setCell(cell, CellType::Open);
                 }
             }
         }
         map.setCell(newPosition, marker);
     }
References Map::getCellType(), Map::numCols(), Map::numRows(), Open, and Map::setCell().
Referenced by main().